SchoolManagement/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolManagement.Models;

namespace SchoolManagement.Controllers
{
    public class CourseController : Controller
    {
        // GET: Course
        public ActionResult Courses()
        {
            var db = new SchoolEntities();
            return View(db.Courses.ToList());
        }
        public ActionResult Create()
        { 
                return View();
            }
           
        }
    }

SchoolManagement/Controllers/InstructorController.cs
using SchoolManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolManagement.Controllers
{
    public class InstructorController : Controller
    {
        // GET: Instructor
        public ActionResult Instructors()
        {
            var db = new SchoolEntities();
            var ins = from i in db.CourseInstructors
                      where i.CourseID == new int()
                      select i;
            return View(db.CourseInstructors.ToList());

        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CourseInstructor newinstructor)
        {

            if (ModelState.IsValid)
            {
                var db = new SchoolEntities();
                db.CourseInstructors.Add(newinstructor);
                db.SaveChanges();

                return RedirectToAction("Instructors");
            }
            else
            {
                return View(newinstructor);
            }
        }
    }
}

SchoolManagement/Controllers/StudentController.cs
using SchoolManagement.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolManagement.Controllers
{
    
    public class StudentController : Controller
    {
        // GET: Student
        public ActionResult StudentProfile()
        {
            var db = new SchoolEntities();
            var i = from p in db.People
                    join sg in db.StudentGrades
                    on p.PersonID equals sg.StudentID
                    join c in db.Courses
                    on sg.CourseID equals c.CourseID
                    select new Tables { student= p,grade=sg,course= c };
            return View(i);
        }
        public ActionResult StudentManagement(DateTime? empty)
        {
            var db = new SchoolEntities();
            var showst = db.People.Where(st => st.HireDate == empty);
            return View(showst);
        }
        public ActionResult StudentGradeManagement()
        {
            var db = new SchoolEntities();
            var mysg = from p in db.People
                       join sgd in db.StudentGrades on p.PersonID equals sgd.StudentID
                       select new sg { students = p, grades = sgd };
            return View(mysg);
        }
            public ActionResult Edit(int? id)
        {
            var db = new SchoolEntities();
            Person people = db.People.Find(id);
            if (people == null)
            {
                return HttpNotFound();
            }
            return View(people);
        }

        [HttpPost]
        public ActionResult Edit(Person people)
        {
            var db = new SchoolEntities();
            if (ModelState.IsValid)
            {
                db.Entry(people).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("StudentGradeManagement");
            }
            return View(people);
        }
    }
    }

SchoolManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SMS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("About Us", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Course Management","Courses","Course")</li>
                    <li>@Html.ActionLink("Student Management","StudentManagement","Student")</li>
                    <li>@Html.ActionLink("Student Profile", "StudentProfile", "Student")</li>
                    <li>@Html.ActionLink("Student Grade Management", "StudentGradeManagement", "Student")</li>
                    <li>@Html.ActionLink("Login", "Login", "Home")</li>
                    <li>@Html.ActionLink("Instructors","Instructors","Instructor")</li>
                    <li>@Html.ActionLink("Edit","Edit","Student")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>